"""
LLM Financial Analyst Module
Uses Azure OpenAI (gpt-4o) to provide intelligent financial analysis.

This module analyzes the comparison_text generated by the dashboard
and provides professional financial insights without hallucinating numbers.
"""

from openai import AzureOpenAI
import os
from typing import Optional


class FinancialAnalystLLM:
    """
    Financial analyst using Azure OpenAI gpt-4o to interpret comparison text.
    Designed to avoid hallucinating numbers by only using provided data.
    """

    def __init__(
        self,
        azure_endpoint: Optional[str] = None,
        api_key: Optional[str] = None,
        api_version: str = "2024-02-15-preview",
        deployment_name: str = "gpt-4o"
    ):
        """
        Initialize the Financial Analyst LLM.

        Args:
            azure_endpoint: Azure OpenAI endpoint URL (from env var AZURE_OPENAI_ENDPOINT if not provided)
            api_key: Azure OpenAI API key (from env var AZURE_OPENAI_KEY if not provided)
            api_version: API version to use
            deployment_name: Name of the deployed model (default: gpt-4o)
        """
        self.azure_endpoint = azure_endpoint or os.getenv("AZURE_OPENAI_ENDPOINT")
        self.api_key = api_key or os.getenv("AZURE_OPENAI_KEY")
        self.api_version = api_version
        self.deployment_name = deployment_name

        if not self.azure_endpoint or not self.api_key:
            raise ValueError(
                "Azure OpenAI endpoint and API key must be provided either as parameters "
                "or via AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_KEY environment variables"
            )

        self.client = AzureOpenAI(
            azure_endpoint=self.azure_endpoint,
            api_key=self.api_key,
            api_version=self.api_version
        )

    def analyze_comparison_text(
        self,
        comparison_text: str,
        max_tokens: int = 1000,
        temperature: float = 0.3
    ) -> str:
        """
        Analyze the comparison text and provide financial insights.

        Args:
            comparison_text: The full comparison text from generate_enhanced_comparison_text_updated()
            max_tokens: Maximum tokens for response (default: 1000)
            temperature: Temperature for generation (0-1, default: 0.3 for reduced hallucination)

        Returns:
            Professional financial analysis text
        """

        system_prompt = """You are a senior financial analyst with expertise in interpreting financial metrics and trends.

CRITICAL RULES TO PREVENT HALLUCINATION:
- ONLY use numbers, percentages, and facts explicitly stated in the provided comparison text
- Do NOT calculate, estimate, infer, or create any numbers not present in the text
- Do NOT make assumptions about data not provided
- If information is missing or unclear, explicitly state "The data does not specify..."
- Focus on interpretation and implications of the data PROVIDED
- Cite specific metrics from the text when making observations

Your role is to:
1. Provide clear, insightful analysis of the financial comparison
2. Identify key drivers and trends based solely on the provided data
3. Offer professional implications and considerations
4. Maintain an analytical, objective tone

Remember: Your credibility depends on accuracy. Only reference what is explicitly stated."""

        user_prompt = f"""Analyze this financial comparison and provide professional insights:

{comparison_text}

Please provide:
1. Executive Summary: Concise overview of the key changes and their significance
2. Key Drivers: Interpretation of what is driving these changes based on the data provided
3. Metric Relationships: Analysis of how Amount, Income, and Ratio changes relate to each other
4. Implications: Professional considerations and potential action items for stakeholders

IMPORTANT: Only reference numbers and facts from the comparison text above. Do not calculate or infer additional metrics."""

        try:
            response = self.client.chat.completions.create(
                model=self.deployment_name,
                messages=[
                    {
                        "role": "system",
                        "content": system_prompt
                    },
                    {
                        "role": "user",
                        "content": user_prompt
                    }
                ],
                max_tokens=max_tokens,
                temperature=temperature
            )

            analysis = response.choices[0].message.content.strip()
            return analysis

        except Exception as e:
            return f"Error generating LLM analysis: {str(e)}"


# Convenience function for easy integration
def analyze_comparison_with_llm(comparison_text: str) -> str:
    """
    Convenience function to get LLM analysis of comparison text.

    Args:
        comparison_text: The full comparison text from generate_enhanced_comparison_text_updated()

    Returns:
        LLM-generated financial analysis
    """
    try:
        analyst = FinancialAnalystLLM()
        return analyst.analyze_comparison_text(comparison_text)

    except Exception as e:
        return f"LLM analysis unavailable: {str(e)}"
