"""
LLM Financial Analyst Module
Uses Azure OpenAI (gpt-4o) to provide intelligent financial analysis.

This module analyzes the comparison_text generated by the dashboard
and provides professional financial insights without hallucinating numbers.
Includes caching for improved performance.
"""

from openai import AzureOpenAI
import os
import hashlib
import json
from datetime import datetime, timedelta
from typing import Optional, Dict, Tuple
from azure.identity import DefaultAzureCredential, get_bearer_token_provider


class FinancialAnalystLLM:
    """
    Financial analyst using Azure OpenAI gpt-4o to interpret comparison text.
    Designed to avoid hallucinating numbers by only using provided data.
    Uses Azure AD authentication via azure_ad_token_provider.
    Includes in-memory caching with TTL for performance optimization.
    """

    # Class-level cache shared across instances
    _cache: Dict[str, Tuple[str, datetime]] = {}
    _cache_ttl_hours: int = 24  # Cache expires after 24 hours

    def __init__(
        self,
        api_version: str = "2024-02-15-preview",
        deployment_name: str = "gpt-4o",
        enable_cache: bool = True
    ):
        """
        Initialize the Financial Analyst LLM.

        Args:
            api_version: API version to use
            deployment_name: Name of the deployed model (default: gpt-4o)
            enable_cache: Enable response caching (default: True)

        Note: Uses Azure AD authentication. Requires AZURE_OPENAI_ENDPOINT environment variable.
        """
        self.azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
        self.api_version = api_version
        self.deployment_name = deployment_name
        self.enable_cache = enable_cache

        if not self.azure_endpoint:
            raise ValueError(
                "Azure OpenAI endpoint must be provided via AZURE_OPENAI_ENDPOINT environment variable"
            )

        # Use Azure AD token provider instead of API key
        token_provider = get_bearer_token_provider(
            DefaultAzureCredential(),
            "https://cognitiveservices.azure.com/.default"
        )

        self.client = AzureOpenAI(
            azure_endpoint=self.azure_endpoint,
            azure_ad_token_provider=token_provider,
            api_version=self.api_version
        )

    @staticmethod
    def _generate_cache_key(comparison_text: str, max_tokens: int, temperature: float) -> str:
        """
        Generate a unique cache key based on input parameters.

        Args:
            comparison_text: The comparison text to analyze
            max_tokens: Maximum tokens for response
            temperature: Temperature for generation

        Returns:
            SHA-256 hash of the input parameters
        """
        cache_input = json.dumps({
            "text": comparison_text,
            "max_tokens": max_tokens,
            "temperature": temperature
        }, sort_keys=True)
        return hashlib.sha256(cache_input.encode()).hexdigest()

    @classmethod
    def _get_from_cache(cls, cache_key: str) -> Optional[str]:
        """
        Retrieve cached response if available and not expired.

        Args:
            cache_key: The cache key to lookup

        Returns:
            Cached response or None if not found/expired
        """
        if cache_key in cls._cache:
            response, timestamp = cls._cache[cache_key]
            # Check if cache entry is still valid
            if datetime.now() - timestamp < timedelta(hours=cls._cache_ttl_hours):
                return response
            else:
                # Remove expired entry
                del cls._cache[cache_key]
        return None

    @classmethod
    def _save_to_cache(cls, cache_key: str, response: str):
        """
        Save response to cache with current timestamp.

        Args:
            cache_key: The cache key
            response: The response to cache
        """
        cls._cache[cache_key] = (response, datetime.now())

    @classmethod
    def clear_cache(cls):
        """Clear all cached responses."""
        cls._cache.clear()

    @classmethod
    def get_cache_stats(cls) -> Dict[str, int]:
        """
        Get cache statistics.

        Returns:
            Dictionary with cache size and valid entries count
        """
        now = datetime.now()
        valid_entries = sum(
            1 for _, timestamp in cls._cache.values()
            if now - timestamp < timedelta(hours=cls._cache_ttl_hours)
        )
        return {
            "total_entries": len(cls._cache),
            "valid_entries": valid_entries
        }

    def analyze_comparison_text(
        self,
        comparison_text: str,
        max_tokens: int = 1000,
        temperature: float = 0.3
    ) -> str:
        """
        Analyze the comparison text and provide financial insights.
        Uses caching to improve performance for repeated queries.

        Args:
            comparison_text: The full comparison text from generate_enhanced_comparison_text_updated()
            max_tokens: Maximum tokens for response (default: 1000)
            temperature: Temperature for generation (0-1, default: 0.3 for reduced hallucination)

        Returns:
            Professional financial analysis text (may be from cache)
        """

        # Check cache first if enabled
        if self.enable_cache:
            cache_key = self._generate_cache_key(comparison_text, max_tokens, temperature)
            cached_response = self._get_from_cache(cache_key)
            if cached_response:
                return cached_response + "\n\n[Response retrieved from cache]"

        system_prompt = """You are a senior financial analyst with expertise in interpreting financial metrics and trends.

CRITICAL RULES TO PREVENT HALLUCINATION:
- ONLY use numbers, percentages, and facts explicitly stated in the provided comparison text
- Do NOT calculate, estimate, infer, or create any numbers not present in the text
- Do NOT make assumptions about data not provided
- If information is missing or unclear, explicitly state "The data does not specify..."
- Focus on interpretation and implications of the data PROVIDED
- Cite specific metrics from the text when making observations

Your role is to:
1. Provide clear, insightful analysis of the financial comparison
2. Identify key drivers and trends based solely on the provided data
3. Offer professional implications and considerations
4. Maintain an analytical, objective tone

Remember: Your credibility depends on accuracy. Only reference what is explicitly stated."""

        user_prompt = f"""Analyze this financial comparison and provide professional insights:

{comparison_text}

Please provide:
1. Executive Summary: Concise overview of the key changes and their significance
2. Key Drivers: Interpretation of what is driving these changes based on the data provided
3. Metric Relationships: Analysis of how Amount, Income, and Ratio changes relate to each other
4. Implications: Professional considerations and potential action items for stakeholders

IMPORTANT: Only reference numbers and facts from the comparison text above. Do not calculate or infer additional metrics."""

        try:
            # For Azure OpenAI, the deployment name is passed via the endpoint configuration
            # The model parameter should match your Azure deployment name
            response = self.client.chat.completions.create(
                model=self.deployment_name,  # This is your Azure deployment name (e.g., "gpt-4o")
                messages=[
                    {
                        "role": "system",
                        "content": system_prompt
                    },
                    {
                        "role": "user",
                        "content": user_prompt
                    }
                ],
                max_tokens=max_tokens,
                temperature=temperature
            )

            analysis = response.choices[0].message.content.strip()

            # Save to cache if enabled
            if self.enable_cache:
                self._save_to_cache(cache_key, analysis)

            return analysis

        except Exception as e:
            return f"Error generating LLM analysis: {str(e)}"


# Convenience function for easy integration
def analyze_comparison_with_llm(comparison_text: str) -> str:
    """
    Convenience function to get LLM analysis of comparison text.

    Args:
        comparison_text: The full comparison text from generate_enhanced_comparison_text_updated()

    Returns:
        LLM-generated financial analysis
    """
    try:
        analyst = FinancialAnalystLLM()
        return analyst.analyze_comparison_text(comparison_text)

    except Exception as e:
        return f"LLM analysis unavailable: {str(e)}"
